# Generated by Django 3.2.8 on 2021-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_cliente', models.IntegerField(max_length=50, null=True)),
                ('codigo_venta', models.IntegerField(max_length=50, null=True)),
                ('ivacompra', models.IntegerField(max_length=50, null=True)),
                ('nitproveedor', models.IntegerField(max_length=50, null=True)),
                ('nombre_producto', models.CharField(max_length=255, null=True)),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
            ],
        ),
    ]
