# Generated by Django 3.2.9 on 2021-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(null=True)),
                ('codigo_producto', models.IntegerField(null=True)),
                ('valor_total', models.FloatField(null=True)),
                ('valor_venta', models.FloatField(null=True)),
                ('valoriva', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('cedula_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_venta', models.IntegerField(null=True)),
                ('iva_venta', models.FloatField(null=True)),
                ('total_venta', models.FloatField(null=True)),
                ('valor_venta', models.FloatField(null=True)),
            ],
        ),
    ]
