# Generated by Django 3.2.9 on 2021-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('codigo_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cedula_cliente', models.IntegerField()),
                ('nitproveedor', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad_producto', models.IntegerField()),
            ],
        ),
    ]
