# Generated by Django 3.2.9 on 2021-11-24 14:30

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_ventas_detalle_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(null=True)),
                ('codigo_producto', models.IntegerField(null=True)),
                ('valor_total', models.FloatField(null=True)),
                ('valor_venta', models.FloatField(null=True)),
                ('valoriva', models.FloatField()),
            ],
        ),
    ]
